### ISSUE TITLE
xg0 is broken

### ISSUE THREAD

**Issue by ekg** [vgteam/xg#1]
It complies, but can't build the graph yet. Stay tuned.

The aim is to allow two kinds of construction: one from GFA (with memory mapping) and disk backed sorting of the edge space to keep memory usage down, and the other from a generic path handle graph.

**Comment by jeizenga** [comment]
What's the status on this? Can I pull this into the handle graph evaluations?

**Comment by ekg** [comment]
I have been able to test this. What are you running into?

**Comment by ekg** [comment]
Oh, this is resolved.
