### ISSUE TITLE
xg construction leaving open file descriptors

### ISSUE THREAD

**Issue by glennhickey** [vgteam/xg#13]
This manifests itself in `vg test` which reaches a limit and starts aborting with `Too many open files: iostream error` after a while.  

Also https://github.com/vgteam/xg/blob/master/src/xg.cpp#L939 seems a little dangerous?  Shouldn't it be a randomly named temp file?

**Comment by glennhickey** [comment]
According to valgrind, they are coming from various mmmultimap incantations such as 
```
Open file descriptor 9: /tmp/xg-bj9GJK/xg-W6O1CI.node_path.mm
==13049==    at 0x4C3DDAE: open (open64.c:47)
==13049==    by 0x226AEA2: xg::XG::index_node_to_path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (fcntl2.h:53)

==13049== Open file descriptor 6: /tmp/xg-bj9GJK/xg-W6O1CI.to_from.mm
==13049==    at 0x4C3DDAE: open (open64.c:47)
==13049==    by 0x22A6F29: mmmulti::map<unsigned long, unsigned long>::index(unsigned long) (fcntl2.h:53)

```

**Comment by ekg** [comment]
You're right. That's a bad file name. There is support for unique temp
files.
